apiVersion: v1
kind: Namespace
metadata:
  name: DEV
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  namespace: DEV
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp-container
        image: vadimv1337/webapp:1.0
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: webapp-service
  namespace: DEV
spec:
  selector:
    app: webapp
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000

